#!/bin/bash

echo -e "\e[1;33m-Este es el apartado ayuda-\e[1;33m"

echo -e "\e[1;33m+------------------------------------------------------------+\e[1;33m"
echo -e "|\e[1;37m      COMANDOS\e[1;33m     |\e[1;37m             DESCRIPCION\e[1;33m                |"
echo -e "\e[1;33m|-------------------|----------------------------------------|\e[1;33m"
echo -e "|\e[1;37mayuda\e[1;33m              |\e[1;37m Muestra los comandos y una descripcion\e[1;33m |"
echo -e "|                   |\e[1;37m de su utilidad                        \e[1;33m |"
echo -e "|-------------------|----------------------------------------|"
echo -e "|\e[1;37marbol              \e[1;33m| \e[1;37mMuestra de manera grafica la jerarquía \e[1;33m|"
echo -e "|                   |\e[1;37m de un directorio que el usuario        \e[1;33m|"
echo -e "|                   |\e[1;37m especifica                             \e[1;33m|"
echo "|-------------------|----------------------------------------|"
echo -e "|\e[1;37minfosis            \e[1;33m| \e[1;37mMuestra informacion del usuario logeado\e[1;33m|"
echo -e "|                   | \e[1;37m, de la memoria ram, la arquitectura y \e[1;33m|"
echo -e "|                   | \e[1;37mla version del sistema operativo.      \e[1;33m|"
echo -e "|-------------------|----------------------------------------|"
echo -e "|\e[1;37mfecha              \e[1;33m| \e[1;37mMuestra la fecha actual                \e[1;33m|"
echo -e "|-------------------|----------------------------------------|"
echo -e "|\e[1;37mhora               \e[1;33m| \e[1;37mMuestra la hora actual                 \e[1;33m|"
echo -e "|-------------------|----------------------------------------|"
echo -e "|\e[1;37mencontrar          \e[1;33m| \e[1;37mEncontrar el archivo que se desee. Se  \e[1;33m|"
echo -e "|                   | \e[1;37mtiene que ingresar el archivo a buscar \e[1;33m|"
echo -e "|                   | \e[1;37my el directorio donde se buscara       \e[1;33m|"
echo -e "|-------------------|----------------------------------------|"
echo -e "|\e[1;37mcreditos           \e[1;33m|\e[1;37m Muestra los creditos de los autores del\e[1;33m|"
echo -e "|                   | \e[1;37mprograma que se esta utilizando en este\e[1;33m|"
echo -e "|                   | \e[1;37mmomento                                \e[1;33m|"
echo -e "|-------------------|----------------------------------------|"
echo -e "|\e[1;37mahorcado         \e[1;33m| \e[1;37mAbrira el juego ahorcado               \e[1;33m|"
echo -e "|-------------------|----------------------------------------|"
echo -e "|\e[1;37mppt                \e[1;33m|\e[1;37m Abrira el piedra, papel o tijeras        \e[1;33m|"
echo -e "|-------------------|----------------------------------------|"
echo -e "|\e[1;37mprebeplayer        \e[1;33m| \e[1;37mAbrira el reproductor grafico llamado  \e[1;33m|"
echo -e "|                   | \e[1;37mprebeshell                             \e[1;33m|"
echo -e "+------------------------------------------------------------+"
