#!/bin/bash

echo "-Este es el apartado ayuda-"

echo "______________________________________________________________"
echo "|Comandos           | Descripcion                            |"
echo "|___________________|________________________________________|"
echo "|ayuda              | Muestra los comandos y una descripcion |"
echo "|                   | de su utilidad                         |"
echo "|___________________|________________________________________|"
echo "|arbol              | Muestra de manera grafica la jerarquía |"
echo "|                   | de un directorio que el usuario        |"
echo "|                   | especifica                             |"
echo "|___________________|________________________________________|"
echo "|infosis            | Muestra informacion del usuario logeado|"
echo "|                   | , de la memoria ram, la arquitectura y |"
echo "|                   | la version del sistema operativo.      |"
echo "|___________________|________________________________________|"
echo "|fecha              | Muestra la fecha actual                |"
echo "|___________________|________________________________________|"
echo "|hora               | Muestra la hora actual                 |"
echo "|___________________|________________________________________|"
echo "|encontrar          | Encontrar el archivo que se desee. Se  |"
echo "|                   | tiene que ingresar el archivo a buscar |"
echo "|                   | y el directorio donde se buscara       |"
echo "|___________________|________________________________________|"
echo "|creditos           | Muestra los creditos de los autores del|"
echo "|                   | programa que se esta utilizando en este|"
echo "|                   | momento                                |"
echo "|___________________|________________________________________|"
echo "|juego1             | Abrira el juego1                       |"
echo "|___________________|________________________________________|"
echo "|juego2             | Abrira el juego2                       |"
echo "|___________________|________________________________________|"
echo "|prebeplayer        | Abrira el reproductor grafico llamado  |"
echo "|                   | prebeshell                             |"
echo "|____________________________________________________________|"



